name: Docs

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*.*.*'

jobs:
  docker-push:
    name: Build API documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF" | cut -d / -f 3 >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Generate docs
        run: make generate-docs

      - name: Push
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
          MESSAGE: "Docs for ${{ steps.version.outputs.contents }} commit {sha}"
          TARGET_DIR: ${{ steps.version.outputs.contents }}
