name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Build and publish package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Configure token
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
        if: ${{ !!env.NPM_TOKEN }}

      - name: Get metadata
        id: meta
        run: |
          version="$(basename "$GITHUB_REF")"

          case "$version" in
            *"-"*) tag="prerelease" ;;
            *) tag="latest" ;;
          esac

          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Pre-publish
        run: make pre-publish VERSION=${{ steps.meta.outputs.version }}

      - name: Build
        run: make build

      - name: Publish
        run: npm publish --provenance --access public --tag ${{ steps.meta.outputs.tag }}
        if: ${{ vars.SKIP_PUBLISH != 'true' }}
