name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get metadata
        id: meta
        run: |
          echo "version=$(basename "$GITHUB_REF")" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: changelog
        run: make generate-release-notes VERSION=${{ steps.meta.outputs.version }}

      - name: Create release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          body_path: ${{ github.workspace }}/RELEASE-NOTES.md
          prerelease: ${{ contains(steps.meta.outputs.version, '-') }}
